// Case-study data, imported from the WordPress export (zicy.WordPress.2026-06-01).
// Generated by gen-cases.mjs — 15 GEO/AEO case studies. Bodies are restyled WP
// article HTML; images are served locally from public/case-studies/. Clients stay
// ANONYMISED pending naming permission (build brief compile flag + §A2).

export interface CaseStudy {
  slug: string;
  indexMeta: string; // index row eyebrow
  eyebrow: string; // detail hero eyebrow
  indexTitle: string; // index row bold line
  big: string; // index row headline stat
  indexSub: string; // index row sub
  h1: string;
  metaTitle: string;
  metaDescription: string;
  datePublished: string;
  dateModified: string;
  bodyHtml: string; // full restyled article HTML
}

export const CASES: CaseStudy[] = [
  {
    slug: "531-ai-citations-ecommerce",
    indexMeta: "eCommerce · 4 months",
    eyebrow: "eCommerce · 4 months",
    indexTitle: "AI citations earned from the ground up",
    big: "531",
    indexSub: "more AI citations · 53.6% ChatGPT SOV",
    h1: "How One eCommerce Brand Boosted Visibility With 531 More AI Citations in 4 Months",
    metaTitle: "531 New AI Citations in 4 Months: eCommerce GEO Case Study — Zicy",
    metaDescription: "Product discovery is shifting from Google to ChatGPT. See how one eCommerce brand earned 531 additional AI citations in just 4 months with a targeted generative engine optimization strategy.",
    datePublished: "2025-08-29",
    dateModified: "2026-05-06",
    bodyHtml: `<p>What if product discovery no longer begins with Google… but with ChatGPT?</p>
<p>Today’s consumers are skipping search engines and going straight to conversational platforms—asking questions like “<em>Which is the best product for X?</em>” or “<em>What’s a good alternative to Y?</em>”</p>
<p>That shift opened a new frontier for an eCommerce brand. We realised that to win online, they had to become the <strong>answer</strong> itself—not just appear near it.</p>
<p>And so they did.</p>
<p>Through a focused AI visibility strategy, we went beyond traditional SEO. We restructured content to be cited by platforms like ChatGPT, Perplexity, and Gemini—and saw a measurable lift in both <strong>visibility and conversions</strong>.</p>
<h2>This is what results looked like..</h2>
<p>Within 4 months, this is what we managed to achieve:</p>
<p><img src="/case-studies/2025/08/How-One-eCommerce-Brand-Boosted-Visibility-With-531-More-AI-Citations-in-4-Months.png" alt="How One eCommerce Brand Boosted Visibility With 531 More AI Citations in 4 Months" loading="lazy" decoding="async" /></p>
<p><strong>AI Platform Citations Skyrocketed</strong></p>
<p>Their brand began appearing as a <strong>go-to recommendation</strong> across multiple generative AI tools:</p>
<ul>
<li><strong>Google AI Overview</strong>: 225 citations (↑168), spread over 67 pages</li>
<li><strong>ChatGPT</strong>: 117 citations (↑118), across 67 pages</li>
<li><strong>Perplexity</strong>: 81 citations (↑78), across 53 pages</li>
<li><strong>Gemini</strong>: 71 citations (↑65), across 69 pages</li>
<li><strong>Copilot (Microsoft)</strong>: 37 citations (↑32), across 27 pages</li>
</ul>
<p><strong>Share of Voice: Beating the Competition on ChatGPT</strong></p>
<p>Brand visibility wasn’t just rising—it was dominating:</p>
<ul>
<li>Their brand secured <strong>53.6% of ChatGPT brand mentions</strong></li>
<li>Top competitor trailed with only <strong>24.2% share</strong></li>
</ul>
<h2>Strategy Breakdown..</h2>
<ol>
<li><strong> AI Citation Engineering</strong></li>
</ol>
<p>Instead of chasing backlinks, the team engineered content that AI models <em>want</em> to cite:</p>
<ul>
<li>Structured brand anchors using entity-based markup.</li>
<li>Answer-driven paragraphs with clear contextual framing.</li>
<li>External linking styled for AI interpretation and traceability.</li>
</ul>
<ol start="2">
<li><strong> Multimodal Content Upgrades</strong></li>
</ol>
<p>They went beyond text:</p>
<ul>
<li>Product pages enhanced with image alt text and visual schema.</li>
<li>Infographics and short-form videos to support AI’s multimodal outputs.</li>
</ul>
<ol start="3">
<li><strong> AEO + Intent-First Content Structure</strong></li>
</ol>
<p>Rather than focusing on keywords, they wrote content that answers questions:</p>
<ul>
<li>Sections answering “which is best for…”, “should I choose…”, “difference between…”</li>
<li>Long-tail semantic triggers and layered FAQ schemas.</li>
<li>Headers crafted for maximum contextual clarity.</li>
</ul>
<ol start="4">
<li><strong> AI Traffic Monitoring Across Platforms</strong></li>
</ol>
<p>Referrer tracking and analytics integration allowed them to track:</p>
<ul>
<li>ChatGPT user flow via chat.openai.com.</li>
<li>Perplexity and Gemini origin traffic.</li>
</ul>
<h2>And the takeaway?</h2>
<p>While others are still optimising for search rankings, this brand bet on a different game:</p>
<p><strong>→ Be the source AI platforms trust and recommend.</strong><br />
<strong> → Make your product the answer.</strong></p>
<p>And that shift in strategy paid off—in both visibility and bottom-line growth.</p>`,
  },
  {
    slug: "increased-ai-users-and-events",
    indexMeta: "eCommerce · AI traffic",
    eyebrow: "eCommerce · AI traffic",
    indexTitle: "AI traffic that converts",
    big: "+406%",
    indexSub: "785 ChatGPT users · 1,816 events",
    h1: "AI Traffic That Converts: 785 ChatGPT Users Driving 1,816 Events (+406%)",
    metaTitle: "785 ChatGPT Users, 1,816 Conversions & 406% Event Growth — Zicy",
    metaDescription: "What happens when customers find you through ChatGPT instead of Google? See how one brand converted 785 AI-referred users into 1,816 tracked events — a 406% increase.",
    datePublished: "2025-09-02",
    dateModified: "2026-05-06",
    bodyHtml: `<p>What if your future customers never Google you—yet still find you?</p>
<p>That’s the new reality of discovery. Platforms like ChatGPT, Gemini, and Perplexity are increasingly where people ask their most urgent questions—and where buying decisions quietly begin.</p>
<p>For our client, the challenge was clear: could they harness these AI-driven moments to generate real users and measurable conversions?</p>
<p>The answer: absolutely.</p>
<p>By aligning content, structure, and tracking for AI-first discoverability, this brand turned experimental AI traffic into a consistent growth engine.</p>
<h2>The results..</h2>
<p><strong>Between January – July 2025, the client saw clear growth across AI platforms:</strong></p>
<p><img src="/case-studies/2025/08/AI-Traffic-That-Converts-785-ChatGPT-Users-Driving-1816-Events-406_1.jpg" alt="AI Traffic That Converts: 785 ChatGPT Users Driving 1,816 Events (+406%)" loading="lazy" decoding="async" /></p>
<p><img src="/case-studies/2025/08/AI-Traffic-That-Converts-785-ChatGPT-Users-Driving-1816-Events-406_2.jpg" alt="AI Traffic That Converts: 785 ChatGPT Users Driving 1,816 Events (+406%)" loading="lazy" decoding="async" /></p>
<ul>
<li><strong>785 users from ChatGPT</strong>, marking a 288.5% increase</li>
<li><strong>149 users from Perplexity.ai</strong>, with 26.0% growth</li>
<li><strong>69 users from Gemini (Google)</strong>, showing 19.9% growth</li>
<li><strong>45 users from Perplexity</strong>, up 9.8%</li>
<li><strong>21 users from Edge (Bing AI),</strong> delivering a 52.4% increase</li>
<li><strong>19 users from Copilot (Microsoft)</strong>, with 19.5% growth</li>
</ul>
<p>And the most important metric—conversion-driving activity:</p>
<ul>
<li><strong>1,966 tracked key events</strong> (from ChatGPT, Perplexity, Gemini, Perpplexity.ai, Edge, Copilot), with a 406.4% jump in key events from ChatGPT alone!</li>
<li>Significant event growth across platforms, including:
<ul>
<li><strong>Gemini</strong>: +42.7%</li>
<li><strong>Perplexity</strong>: +51.7%</li>
<li><strong>Edge</strong>: +54.7%</li>
<li><strong>Copilot</strong>: +36.8%</li>
</ul>
</li>
</ul>
<h2>How we did it…</h2>
<ol>
<li><strong> Rethinking Research</strong></li>
</ol>
<p>Instead of starting with keywords, the team:</p>
<ul>
<li>Pinpointed <strong>customer pain points</strong> and USP-led messaging.</li>
<li>Built <strong>topic clusters</strong> around high-intent themes.</li>
<li><strong>Analysed competitor mentions</strong> inside AI responses—not just SERPs.</li>
<li>Focused efforts on <strong>bottom-funnel content</strong> to drive leads, not vanity clicks.</li>
</ul>
<ol start="2">
<li><strong> Making Content AI-Readable</strong></li>
</ol>
<p>To increase the chance of being cited and surfaced:</p>
<ul>
<li>Added <strong>concise takeaway sections</strong> for snippet-style answers.</li>
<li>Structured content in an <strong>“answer-first” inverted pyramid</strong> style.</li>
<li>Embedded FAQ blocks by addressing common questions.</li>
</ul>
<ol start="3">
<li><strong> Technical SEO With AI in Mind</strong></li>
</ol>
<p>Optimisations ensured AI models could easily interpret content:</p>
<ul>
<li><strong>Schema markup</strong> rolled out across all product/service pages.</li>
<li>Fixed <strong>header hierarchies</strong> (H1–H6) for logical flow.</li>
<li><strong>Image alt text</strong> improved for clarity.</li>
<li><strong>Robots.txt</strong> updated to give AI crawlers full access to priority pages.</li>
</ul>
<ol start="4">
<li><strong> Measuring AI Traffic Directly</strong></li>
</ol>
<p>To avoid guesswork, the brand established:</p>
<ul>
<li>Tracking systems to isolate <strong>AI-originating traffic.</strong></li>
<li>Behavioural analysis to map <strong>AI-driven conversion journeys.</strong></li>
<li>A feedback cycle where insights shaped <strong>new content creation.</strong></li>
</ul>
<h2>The takeaway</h2>
<p>AI platforms aren’t just a novelty. They’re a growing part of the customer journey.</p>
<p>By adapting both content and technical infrastructure to this new search environment, the brand positioned itself not just to be found, but to be trusted and chosen.</p>`,
  },
  {
    slug: "ai-optimised-content",
    indexMeta: "eCommerce · content",
    eyebrow: "eCommerce · content",
    indexTitle: "Precision over volume",
    big: "290%",
    indexSub: "more clicks · 457% more impressions",
    h1: "How AI-Optimised Content Drove 290% More Clicks and 457% More Impressions for an eCommerce Brand",
    metaTitle: "AI-Optimised Content: 290% More Clicks & 457% More Impressions — Zicy",
    metaDescription: "Precision over volume. Discover how AI-optimised content drove 290% more clicks and 457% more impressions for an eCommerce brand without increasing publishing frequency.",
    datePublished: "2025-09-02",
    dateModified: "2026-05-06",
    bodyHtml: `<p>Most brands publish more content when they want more traffic.</p>
<p>But what if the real growth lever isn’t quantity—it's precision?</p>
<p>For our client, an eCommerce brand, the turning point came when we shifted the focus from producing endless blogs to restructuring and enriching existing pages. By aligning with how AI tools and Google interpret user intent, we uncovered hidden opportunities sitting in plain sight.</p>
<p>The outcome? Not incremental change, but a step-level jump in performance.</p>
<h2>The results (June 1 – June 30, 2025 vs June 1 – June 30, 2024)</h2>
<p>Here’s the change we saw in a YOY comparison:</p>
<p><img src="/case-studies/2025/08/How-AI-Optimised-Content-Drove-290-More-Clicks-and-457-More-Impressions-for-an-eCommerce-Brand.jpg" alt="How AI-Optimised Content Drove 290% More Clicks and 457% More Impressions for an eCommerce Brand" loading="lazy" decoding="async" /></p>
<ul>
<li><strong>Monthly clicks</strong> surged <strong>290.32%</strong>, climbing from <strong>1.55K to 6.05K</strong></li>
<li><strong>Monthly impressions</strong> grew <strong>457.14%</strong>, from <strong>105K to 585K</strong></li>
<li><strong>Average search position</strong> improved by <strong>15 spots</strong>, from <strong>31.1 to 16.1</strong></li>
</ul>
<h2>What we did differently</h2>
<ol>
<li><strong> Intent-Led Keyword Clustering</strong></li>
</ol>
<p>We used AI-driven clustering to spotlight product and category pages with untapped ranking potential, matching them directly with transaction-focused queries.</p>
<ol start="2">
<li><strong> Layered Content Enhancements</strong></li>
</ol>
<p>Instead of adding volume, we enriched key pages with:</p>
<ul>
<li>FAQs tuned for buyer questions</li>
<li>Short trust-building snippets</li>
<li>Contextual details that improved semantic depth</li>
</ul>
<ol start="3">
<li><strong> Intelligent Internal Linking</strong></li>
</ol>
<p>AI-guided mapping connected product pages, parent categories, and blogs into a logical content web, amplifying crawl efficiency and signalling stronger relevance to search engines.</p>
<ol start="4">
<li><strong> Continuous Optimisation Loop</strong></li>
</ol>
<p>Every 30 days, we applied micro-adjustments informed by weekly AI performance tracking—ensuring content evolved with user behaviour and SERP shifts.</p>
<ol start="5">
<li><strong> Entity-Level Authority Signals</strong></li>
</ol>
<p>We embedded structured metadata and NLP-driven entity optimisation so that search engines could better associate the brand with topical authority in its product niches.</p>
<h2>The big lesson..</h2>
<p>This case study wasn’t about writing more. It was about writing smarter.</p>
<p>AI became the lens through which we refined strategy: surfacing content gaps, aligning with buyer intent, and structuring pages so they were easy for both users and algorithms to understand.</p>
<p>The takeaway? Brands that combine human strategy with AI precision don’t just compete in search—they leap ahead.</p>
<p>If your pages aren’t yet AI-optimised, your competitors may already be one step closer to capturing your audience.</p>`,
  },
  {
    slug: "increasing-ai-citations",
    indexMeta: "Multi-category · GEO",
    eyebrow: "Multi-category · GEO",
    indexTitle: "From zero to 99 AI citations",
    big: "12,800%",
    indexSub: "more traffic · 0 → 99 citations",
    h1: "From Zero to 99 AI Citations: How This Brand Captured 12,800% More Traffic",
    metaTitle: "From Zero to 99 AI Citations: 12,800% More Traffic With GEO — Zicy",
    metaDescription: "Find out how one brand went from zero AI citations to 99 — generating 12,800% more traffic by becoming the source AI platforms reference in generative search results.",
    datePublished: "2025-09-08",
    dateModified: "2026-05-06",
    bodyHtml: `<p>In today’s AI-first search landscape, the biggest win isn’t ranking on page one—it’s becoming the source AI platforms cite.</p>
<p>That’s exactly the transformation we engineered for a client in architectural services.</p>
<p>Starting with zero AI mentions, they quickly built a reputation as a trusted authority across ChatGPT, Gemini, Perplexity, and Copilot—all without a single paid ad.</p>
<p>The project began in <strong>December 2024</strong> with one clear goal: <strong>turn the brand into an answer</strong>, <strong>not just a search result</strong>.</p>
<h2>The Results (as of August 2025)</h2>
<p><img src="/case-studies/2025/09/From-Zero-to-99-AI-Citations.png" alt="From Zero to 99 AI Citations" loading="lazy" decoding="async" /></p>
<p><img src="/case-studies/2025/09/From-Zero-to-99-AI-Citations_2.png" alt="From Zero to 99 AI Citations" loading="lazy" decoding="async" /></p>
<p><strong>AI Citations Secured: 99</strong></p>
<ul>
<li><strong>ChatGPT</strong>: 41 citations on 12 pages (+39 vs baseline)</li>
<li><strong>Google AI Overview</strong>: 20 citations on 17 pages (+19)</li>
<li><strong>Gemini</strong>: 16 citations on 15 pages (+14)</li>
<li><strong>Perplexity</strong>: 15 citations on 7 pages (+13)</li>
<li><strong>Copilot</strong>: 7 citations on 3 pages (+5)</li>
</ul>
<p><strong>AI Traffic Performance</strong></p>
<ul>
<li><strong>Total AI-sourced users</strong>: 278</li>
<li><strong>New AI users</strong>: 235</li>
<li><strong>Year-on-year AI traffic growth</strong>: +12,800%</li>
<li><strong>Year-on-year AI events growth</strong>: +21,800%</li>
<li><strong>Key events from AI users</strong>: 29</li>
</ul>
<p><strong>Branded vs Non-Branded Impact</strong></p>
<ul>
<li>Branded queries saw steady growth.</li>
<li><strong>Non-branded queries surged</strong>, confirming stronger discovery via AI-driven responses.</li>
</ul>
<h2>The Strategy Behind the Growth</h2>
<ol>
<li><strong> Restructuring for AI Discovery</strong></li>
</ol>
<ul>
<li>Expanded content into <strong>long-form Q&amp;A formats</strong> designed for snippet extraction.</li>
<li>Deployed <strong>schema.org markup</strong> including FAQ, How-To, and Author schemas.</li>
</ul>
<ol start="2">
<li><strong> Entity Optimisation for Generative Engines</strong></li>
</ol>
<ul>
<li>Strengthened topical authority by mapping content to <strong>Google’s Knowledge Graph entities</strong>.</li>
<li>Improved brand mention consistency to align with <strong>AI Overview inclusion criteria</strong>.</li>
<li>Built <strong>internal linking structures</strong> to clarify entity relationships across the site.</li>
</ul>
<ol start="3">
<li><strong> Monitoring &amp; Testing Across AI Platforms</strong></li>
</ol>
<ul>
<li>Tracked presence inside <strong>Google AI Overview, ChatGPT responses, Gemini, Perplexity, and Copilot</strong>.</li>
<li>Conducted iterative <strong>Generative Engine Optimisation (GEO) testing</strong> to refine visibility triggers</li>
</ul>
<ol start="4">
<li><strong> Zero-Click AI Traffic Tracking</strong></li>
</ol>
<ul>
<li>
<ul>
<li>Designed a custom analytics dashboard to separate:
<ul>
<li>AI-generated answer referrals</li>
<li>AI-driven search traffic</li>
</ul>
</li>
<li>Monitored <strong>citations</strong> → <strong>sessions</strong> → <strong>conversions</strong> pipeline for attribution clarity</li>
</ul>
</li>
</ul>
<h2><em>Key Takeaway</em></h2>
<p>Ranking on Google is no longer the endgame. In an era where AI answers shape buying journeys, being cited directly inside these responses is what drives discovery.</p>
<p>This client’s journey proves that with the right AEO + GEO framework, even a brand starting from zero can achieve authority inside AI ecosystems, translating into visibility, traffic, and meaningful conversions.</p>`,
  },
  {
    slug: "aeo-case-study-brand-mentions-ai-cited-product-pages",
    indexMeta: "eCommerce · AEO/GEO",
    eyebrow: "eCommerce · AEO/GEO",
    indexTitle: "AI-cited product pages",
    big: "1,186%",
    indexSub: "faster growth · 74.6% mention coverage",
    h1: "1,186% Faster Growth, 74.6% Brand Mention Coverage & AI-Cited Product Pages (Answer/Generative Engine Optimization)",
    metaTitle: "1,186% Faster Growth & 74.6% AI Brand Mention Coverage — Zicy",
    metaDescription: "See how one brand used answer engine and generative engine optimization to achieve 1,186% faster growth and have its product pages cited by ChatGPT, Gemini, and Perplexity.",
    datePublished: "2026-01-21",
    dateModified: "2026-05-06",
    bodyHtml: `<p><strong><em>What if ChatGPT, Gemini, or Perplexity quietly decides which brand is trustworthy, which product is relevant, and which page deserves to be cited, before a shopper even lands on your site?</em></strong></p>
<p>That was the question facing this U.S.-based eCommerce brand selling contact lenses online.</p>
<p>And instead of guessing how AI systems perceive their brand, they chose to measure it.</p>
<h2><strong>Results Snapshot (Measured via Zicy + GA4)</strong></h2>
<p><strong>AI &amp; AEO Traffic Performance</strong></p>
<ul>
<li><strong>AEO traffic grew 1,186% faster than total site traffic.</strong></li>
<li><strong>AEO growth rate:</strong> +1207%</li>
<li><strong>Total site growth:</strong> +21%</li>
<li><strong>96.6% of AI-driven traffic came from ChatGPT.</strong></li>
</ul>
<p><img src="/case-studies/2026/01/trafic-by-AI-sources.png" alt="traffic by AI source" loading="lazy" decoding="async" /></p>
<p><strong>Engagement &amp; Product Page Quality</strong></p>
<ul>
<li><strong>AEO-driven product pages recorded high engagement with</strong> multiple top pages showing <strong>89%–94% engagement rates.</strong></li>
<li>AI-referred users consistently landed on <strong>commercial product URLs</strong>, not blog content.</li>
</ul>
<p><img src="/case-studies/2026/01/top-performance-of-landing-pages.png" alt="top performance of landing pages" loading="lazy" decoding="async" /></p>
<p><strong>AI Visibility &amp; Brand Authority</strong></p>
<ul>
<li><strong>Brand Mention Coverage:</strong> <strong>74.58%</strong> (44 out of 59 AI responses mentioned the brand).</li>
<li><strong>Website Citation Coverage:</strong> <strong>45.76%</strong>.</li>
<li><strong>Average AI Ranking:</strong> <strong>2.59</strong> across tracked prompts.</li>
<li><strong>Share of Voice:</strong> <strong>18.11%</strong>, leading the competitive set.</li>
</ul>
<p><img src="/case-studies/2026/01/AI-visibility-report.png" alt="AI visibility report" loading="lazy" decoding="async" /></p>
<p><img src="/case-studies/2026/01/competitive-AI-performance.png" alt="competitive AI performance" loading="lazy" decoding="async" /></p>
<p><strong>Competitive AI Performance</strong></p>
<ul>
<li>Ranked <strong>#1 among 5 tracked competitors</strong> for brand mentions, website citations, and overall AI share of voice.</li>
</ul>
<h2><strong>What We Did?</strong></h2>
<ol>
<li><strong>AI Visibility Diagnostics (Before Writing Anything)</strong>
<ul>
<li>Mapped how ChatGPT, Gemini, etc., already referenced the brand.</li>
<li>Identified gaps between high-converting products and AI-cited products.</li>
<li>Benchmarked AI share of voice against eCommerce competitors.</li>
</ul>
</li>
<li><strong>Product-Level AEO Optimisation</strong>
<ul>
<li>Re-structured product pages for answer clarity, not keyword density.</li>
<li>Added AI-readable attributes (use cases, comparisons, etc.).</li>
<li>Ensured each product page could resolve transactional questions that AI systems tend to surface.</li>
<li>Tightened on-page language to remove ambiguity.</li>
<li>Balanced commercial intent with neutral, factual phrasing preferred by LLMs.</li>
</ul>
</li>
<li><strong>Continuous Prompt &amp; Platform Tracking</strong>
<ul>
<li>Tracked visibility across real shopping-style prompts.</li>
<li>Monitored ranking, mentions, citations, and share of voice over time.</li>
</ul>
</li>
</ol>
<h2>Why Tracking AI Visibility Now Matters (Not Later)</h2>
<ul>
<li><strong>AI answers are already influencing buying decisions</strong>, especially for comparison-heavy products.</li>
<li>Traditional SEO metrics don’t show:
<ul>
<li>Whether your brand is mentioned.</li>
<li>Whether your product page is cited.</li>
<li>Whether AI prefers you or your competitor.</li>
</ul>
</li>
<li>Without visibility tracking, <strong>brands mistake traffic drops as randomness</strong>.</li>
<li>With visibility data, optimisation becomes <strong>intent-aligned</strong>, <strong>defensible</strong>, and <strong>repeatable</strong></li>
</ul>
<h2>The Bigger Shift This Case Study Reveals</h2>
<p>This brand didn’t “chase AI traffic.” They <strong>measured how AI understood them- and corrected it</strong>.</p>
<p>As discovery shifts from rankings to recommendations, the winners won’t be the loudest brands. They’ll be the ones AI systems trust enough to cite.</p>
<p><strong>Track it. Understand it. Optimise for it—with Zicy.</strong></p>
<p><em>For more AEO/GEO case studies, visit us at <a href="/case-studies">https://www.zicy.com/case-studies</a> </em></p>`,
  },
  {
    slug: "aeo-case-study-brand-mentions-website-citation-coverage-in-ai-results",
    indexMeta: "eCommerce · AEO/GEO",
    eyebrow: "eCommerce · AEO/GEO",
    indexTitle: "Mentions where competitors led on search",
    big: "82.9%",
    indexSub: "brand mentions · 37.14% citations",
    h1: "How an eCommerce Client Achieved 82.9% Brand Mentions and 37.14% Website Citation Coverage in AI Results",
    metaTitle: "82.9% Brand Mentions & 37.14% AI Citation Coverage for eCommerce — Zicy",
    metaDescription: "Learn how an eCommerce brand achieved 82.9% brand mention coverage and 37.14% website citation coverage in AI results — even while competitors led on traditional search.",
    datePublished: "2026-01-27",
    dateModified: "2026-05-06",
    bodyHtml: `<p><strong>What if your eCommerce competitors aren’t outranking you on Google, but AI systems are still recommending them more often?</strong></p>
<p>The real competition isn’t page one anymore, but who shows up in ChatGPT answers, Gemini summaries, and AI shopping recommendations.</p>
<p>That was the blind spot for this eCommerce brand. Search performance looked stable. Conversions were healthy. But AI-driven discovery? Completely invisible.</p>
<p>Using <strong>Zicy</strong>, the brand stopped guessing how AI systems perceived them and started measuring, comparing, and correcting it.</p>
<h2>Results Snapshot (Measured via Zicy)</h2>
<p><strong>AI Visibility &amp; Brand Presence</strong></p>
<ul>
<li><strong>Brand Mention Coverage:</strong> <strong>82.86%</strong></li>
<li><strong>Website Citation Coverage:</strong> <strong>37.14%</strong></li>
<li><strong>Average AI Ranking:</strong> <strong>2.79</strong> across tracked prompts.</li>
<li><strong>Share of Voice:</strong> <strong>8.86%</strong>, the highest among tracked competitors.</li>
</ul>
<p><img src="/case-studies/2026/01/brand-performance.png" alt="brand performance" loading="lazy" decoding="async" /></p>
<p><strong>Competitive AI Performance</strong></p>
<ul>
<li>Ranked <strong>#1 in Share of Voice</strong> against 5 direct eCommerce competitors.</li>
<li>Outperformed competitors on brand mentions, citation presence, overall AI recommendation visibility.</li>
</ul>
<p><img src="/case-studies/2026/01/Competitive-AI-Performance-2.png" alt="Competitive AI Performance" loading="lazy" decoding="async" /></p>
<p><strong>Prompt-Level Visibility</strong></p>
<ul>
<li>Strong presence across <strong>commercial and evaluative prompts.</strong></li>
<li>Multiple prompts achieving <strong>5/5 brand mention coverage</strong>, top-3 AI positions.</li>
</ul>
<p><img src="/case-studies/2026/01/Prompt-Level-Visibility.png" alt="Prompt-Level Visibility" loading="lazy" decoding="async" /></p>
<h2>What We Did (Strategy Breakdown)</h2>
<ol>
<li><strong>Competitive AI Benchmarking</strong></li>
</ol>
<ul>
<li>Compared the brand vs competitors across mentions, citations, rankings, and share of voice.</li>
<li>Identified where competitors were winning without higher search rankings.</li>
</ul>
<ol start="2">
<li><strong>Prompt-Level AEO Analysis</strong></li>
</ol>
<ul>
<li>Tracked real buyer-style prompts used in AI systems.</li>
<li>Mapped which prompts triggered brand mentions, and which didn’t.</li>
<li>Used gaps to prioritise optimisation.</li>
</ul>
<ol start="3">
<li><strong>Brand–Entity Reinforcement</strong></li>
</ol>
<ul>
<li>Strengthened brand-product associations so AI systems could confidently reference the site.</li>
<li>Reduced ambiguity that often causes AI to cite “neutral” competitors instead.</li>
</ul>
<ol start="4">
<li><strong>Continuous Visibility Monitoring</strong></li>
</ol>
<ul>
<li>Monitored changes in AI rankings and mentions over time.</li>
<li>Used movement (not assumptions) to validate optimisation impact.</li>
</ul>
<h2>Why Tracking This Matters Now?</h2>
<ul>
<li>AI systems don’t “rank” brands the way search engines do. They recommend.</li>
<li>Visibility loss doesn’t show up as a traffic drop until it’s already too late.</li>
<li>Without tracking:
<ul>
<li>You don’t know <em>which prompts you’re losing.</em></li>
<li>You don’t know <em>which competitor AI prefers.</em></li>
<li>You don’t know <em>why.</em></li>
</ul>
</li>
<li>With tracking:
<ul>
<li>Optimisation becomes targeted, not reactive.</li>
<li>Competitive gaps become measurable, not anecdotal.</li>
</ul>
</li>
</ul>
<h2>The Shift This Case Study Makes Clear</h2>
<p>This brand didn’t overhaul its entire site. They simply answered one question clearly: <strong>“How does AI see us compared to everyone else?”</strong></p>
<p>Once that was visible, improvement became inevitable.</p>
<p>As eCommerce discovery shifts from search results to AI answers, brands that measure AI visibility early won’t just compete better, but will be recommended more often.</p>
<p><strong>By tracking AI visibility with tools such as Zicy, brands can replace assumptions with evidence as discovery models change.</strong></p>
<p><em>For more AEO/GEO case studies, visit us at </em><br />
<a href="/case-studies"><em>https://www.zicy.com/case-studies</em></a></p>`,
  },
  {
    slug: "aeo-case-study-brand-mentions-ai-citations-share-of-voice",
    indexMeta: "Education · AEO/GEO",
    eyebrow: "Education · AEO/GEO",
    indexTitle: "Knowledge-led authority in AI answers",
    big: "62.96%",
    indexSub: "mentions · 23.04% share of voice",
    h1: "How an Education Brand Achieved 62.96% Mentions, 36.51% Citation Coverage & 23.04% AI Share of Voice",
    metaTitle: "How an Education Brand Got 62.96% AI Mentions & 23% Share of Voice — Zicy",
    metaDescription: "Discover how a knowledge-led education brand achieved 62.96% AI mention coverage, 36.51% citation coverage, and 23.04% AI share of voice using GEO and AEO strategies.",
    datePublished: "2026-02-04",
    dateModified: "2026-05-06",
    bodyHtml: `<p>AI-driven discovery is no longer limited to product recommendations.</p>
<p>For service-based organisations, especially in knowledge-led sectors, AI systems increasingly shape which brands are surfaced, referenced, and compared.</p>
<p>This case study looks at how an education sector services provider used AI visibility measurement to understand where it appeared in AI-generated answers, and how that visibility translated into meaningful year-over-year traffic growth.</p>
<h2><strong>Results Snapshot (Zicy + GA4)</strong></h2>
<p><strong>AI Visibility &amp; Authority Signals</strong></p>
<ul>
<li><strong>Brand Mention Coverage:</strong> <strong>62.96%</strong></li>
<li><strong>Website Citation Coverage:</strong> <strong>36.51%</strong></li>
<li><strong>Average AI Ranking:</strong> <strong>2.44</strong> across tracked prompts.</li>
<li><strong>Share of Voice:</strong> <strong>23.04%</strong>, the highest among competing brands.</li>
</ul>
<p><img src="/case-studies/2026/02/AI-visibility-report-972x1024.png" alt="AI visibility report" loading="lazy" decoding="async" /></p>
<p><strong>Competitive AI Performance</strong></p>
<ul>
<li>Ranked <strong>#1 in AI Share of Voice</strong> against 5 competitors.</li>
<li>Most consistent visibility across brand mentions, website citations, and top-3 AI rankings.</li>
</ul>
<p><img src="/case-studies/2026/02/competitive-AI-report-1024x327.png" alt="competitive AI report" loading="lazy" decoding="async" /></p>
<p><img src="/case-studies/2026/02/tracked-prompts-1024x572.png" alt="tracked prompts" loading="lazy" decoding="async" /></p>
<p><strong>Year-over-Year AI Traffic Impact (GA4)</strong></p>
<ul>
<li><strong>AI-driven sessions increased by over 12,507% YoY (2024 vs. 2025).</strong></li>
<li><strong>Engaged sessions grew by more than 12,845%.</strong></li>
<li>ChatGPT emerged as the dominant AI traffic source, with incremental growth from Perplexity and Gemini.</li>
</ul>
<p><img src="/case-studies/2026/02/AI-traffic-784x1024.png" alt="AI traffic" loading="lazy" decoding="async" /></p>
<h2><strong>What Was Done (Strategy Breakdown)</strong></h2>
<ol>
<li><strong>AI Visibility Baseline</strong></li>
</ol>
<ul>
<li>Measured brand presence across 39 real-world prompts and 5 AI platforms.</li>
<li>Established benchmarks for mentions, citations, rankings, and share of voice.</li>
<li>Identified where competitors were referenced instead, despite similar positioning.</li>
</ul>
<ol start="2">
<li><strong>Prompt-Level Performance Analysis</strong></li>
</ol>
<ul>
<li>Tracked how individual prompts performed across platforms.</li>
<li>Highlighted prompts with strong rankings but weak brand mentions.</li>
<li>Used these gaps to prioritise optimisation efforts.</li>
</ul>
<ol start="3">
<li><strong>Authority &amp; Clarity Alignment</strong></li>
</ol>
<ul>
<li>Refined key service pages to improve attribution clarity.</li>
<li>Strengthened brand–entity signals relied on by AI systems.</li>
<li>Reduced ambiguity that often leads to generic or competitor citations.</li>
</ul>
<ol start="4">
<li><strong>Continuous Measurement</strong></li>
</ol>
<ul>
<li>Monitored visibility trends over time rather than relying on one-off snapshots.</li>
<li>Used changes in rankings, mentions, and citations to validate progress.</li>
</ul>
<h2><strong>Why Tracking AI Visibility Matters for Service Brands</strong></h2>
<ul>
<li>AI systems increasingly act as <strong>filters</strong>, not just information sources.</li>
<li>Visibility gaps often don’t show up in traditional analytics until later stages.</li>
<li>Without AI visibility tracking:
<ul>
<li>Brands don’t know where they’re excluded from recommendations.</li>
<li>Competitive losses happen quietly.</li>
</ul>
</li>
<li>With tracking:
<ul>
<li>Visibility becomes measurable.</li>
<li>Optimisation aligns with real discovery behaviour, not assumptions.</li>
</ul>
</li>
</ul>
<p>This organisation didn’t focus on chasing rankings alone. They focused on understanding how AI systems surface, compare, and reference brands in their category.</p>
<p>Platforms like <a href="/">Zicy</a> help make this layer observable, so organisations can adapt as discovery models continue to evolve.</p>
<p><em>For more AEO/GEO case studies, visit us at </em><a href="/case-studies"><em>https://www.zicy.com/case-studies</em></a></p>`,
  },
  {
    slug: "aeo-geo-case-study-ai-visibility-ecommerce-growth",
    indexMeta: "eCommerce · AEO/GEO",
    eyebrow: "eCommerce · AEO/GEO",
    indexTitle: "AI visibility, rebuilt for growth",
    big: "1,119%",
    indexSub: "AI traffic growth · 68.97% mentions",
    h1: "How 1,119% AI Growth and 68.97% Brand Mentions Changed eCommerce Visibility",
    metaTitle: "AI Traffic Growth & More Brand Mentions for eCommerce Brand — Zicy",
    metaDescription: "Discover how an eCommerce brand achieved 1,119% AI traffic growth + 68.97% brand mentions by optimising visibility across AI platforms like ChatGPT and Gemini.",
    datePublished: "2026-03-05",
    dateModified: "2026-05-06",
    bodyHtml: `<p><strong><em>If AI were asked to recommend products in your category today, would you lead?</em></strong></p>
<p>AI platforms are no longer peripheral traffic sources. For many eCommerce brands, they are becoming high-intent entry points, especially for product discovery and comparison.</p>
<p>This case study explores how one eCommerce brand measured and improved its AI visibility, and how that visibility translated into significant year-over-year AI traffic growth.</p>
<h2>Results snapshot (Zicy + GA4)</h2>
<h3>AI Traffic Growth (Year-over-Year – GA4)</h3>
<ul>
<li><strong>Active Users:</strong> Grew by <strong>1,119%</strong></li>
<li><strong>Sessions:</strong> Grew by <strong>886%</strong></li>
<li><strong>ChatGPT traffic alone:</strong>
<ul>
<li>Active users grew <strong>1,140%</strong></li>
<li>Sessions increased <strong>882%</strong></li>
</ul>
</li>
<li><strong>Gemini traffic</strong> also showed triple-digit growth</li>
</ul>
<p><img src="/case-studies/2026/03/image-7.png" alt="AI Traffic Growth" loading="lazy" decoding="async" /></p>
<h3>AI Visibility &amp; Authority Signals (Zicy)</h3>
<ul>
<li><strong>Brand Mention Coverage:</strong> <strong>68.97%</strong> (40 out of 58 AI responses included the brand)</li>
<li><strong>Website Citation Coverage:</strong> <strong>20.69%</strong></li>
<li><strong>Average AI Ranking:</strong> <strong>2.15</strong></li>
<li><strong>Share of Voice:</strong> <strong>8.42%</strong></li>
</ul>
<p><img src="/case-studies/2026/03/AI-Visibility-Authority-Signals.png" alt="AI Visibility &amp; Authority Signals" loading="lazy" decoding="async" /></p>
<h3>2-Week Visibility Trend</h3>
<ul>
<li><strong>Share of Voice increased from 7.2% to 8.4%</strong></li>
<li><strong>Brand Mentions grew from 96 to 362</strong></li>
</ul>
<p><img src="/case-studies/2026/03/AI-visibility-report.png" alt="AI visibility report" loading="lazy" decoding="async" /></p>
<h3>Competitive AI Performance</h3>
<ul>
<li>Ranked <strong>#2.1 average AI position</strong>, ahead of several competitors.</li>
<li>Maintained <strong>higher ranking consistency</strong> than brands with larger citation counts.</li>
<li>Competitors showed higher raw citation numbers but weaker ranking stability.</li>
</ul>
<p><img src="/case-studies/2026/03/Competitive-AI-Performance.png" alt="Competitive AI Performance" loading="lazy" decoding="async" /></p>
<h2><strong>What was done (Strategy Breakdown)</strong></h2>
<ol>
<li>
<h3><strong> AI Visibility Baseline &amp; Competitive Mapping</strong></h3>
</li>
</ol>
<ul>
<li>Measured brand mentions, citations, rankings, and share of voice across tracked prompts.</li>
<li>Identified prompts where competitors dominated despite similar product positioning.</li>
<li>Prioritised optimisation around high-intent commercial queries.</li>
</ul>
<ol start="2">
<li>
<h3><strong> Product &amp; Category-Level AEO Optimisation</strong></h3>
</li>
</ol>
<ul>
<li>Improved clarity in product and collection pages.</li>
<li>Structured content around comparison logic, use-case framing, clear differentiation cues.</li>
</ul>
<ol start="3">
<li>
<h3><strong> Prompt-Level Monitoring</strong></h3>
</li>
</ol>
<ul>
<li>Tracked performance across individual buyer-style prompts.</li>
<li>Identified which prompts triggered strong brand mention coverage.</li>
<li>Closed visibility gaps on weaker prompts.</li>
</ul>
<ol start="4">
<li>
<h3><strong> Continuous Iteration</strong></h3>
</li>
</ol>
<ul>
<li>Monitored weekly movement in rankings and share of voice.</li>
<li>Validated improvements using measurable deltas.</li>
</ul>
<h2>What this case study shows….</h2>
<p>AI visibility is not a vanity metric. It is increasingly tied to traffic quality and acquisition shifts.</p>
<p>This eCommerce brand did not rely solely on SEO rankings. They measured how AI systems referenced them, and adjusted accordingly.</p>
<p>As discovery continues shifting toward AI-generated answers, understanding where and how a brand appears in those answers becomes a competitive necessity.</p>
<p>Platforms like <a href="/"><strong>Zicy</strong></a> make that visibility observable, so brands can respond as AI-driven discovery evolves.</p>
<p><em>For more AEO/GEO case studies, visit us at </em><a href="/case-studies"><em>https://www.zicy.com/case-studies</em></a></p>`,
  },
  {
    slug: "aeo-case-study-aesthetic-clinic-ai-visibility",
    indexMeta: "Healthcare / aesthetics",
    eyebrow: "Healthcare / aesthetics",
    indexTitle: "Local category leadership",
    big: "52%",
    indexSub: "mentions · SOV 5.4% → 9.4%",
    h1: "How an Aesthetic Clinic Drove 52% Mentions, 29.75% Citations & Increased AI Share of Voice from 5.4% to 9.4%",
    metaTitle: "Aesthetic Clinic Increased AI Mentions & Share of Voice — Zicy",
    metaDescription: "Discover the AEO/GEO strategy that drove 52% brand mentions, 29.75% citations, and boosted AI share of voice from 5.4% to 9.4% for a Malaysian Aethetic Clinic!",
    datePublished: "2026-02-24",
    dateModified: "2026-05-06",
    bodyHtml: `<p>In the aesthetic industry, discovery increasingly begins inside AI answers, and not search result pages.</p>
<p>When prospective patients ask AI platforms about treatments, safety, comparisons, or suitability, the brands that appear in those responses shape perception long before a website visit.</p>
<p>This aesthetic clinic wanted to understand a simple but critical question: <em><strong>How often is our brand actually being surfaced in AI answers, and how is that changing over time?</strong></em></p>
<p><strong>AI Visibility &amp; Authority Metrics</strong></p>
<ul>
<li><strong>Brand Mention Coverage: 52%</strong></li>
<li><strong>Website Citation Coverage: 29.75%</strong></li>
<li><strong>Average AI Ranking: 1.89</strong> across 135 tracked prompts</li>
<li><strong>Share of Voice: 9.33%</strong> overall</li>
</ul>
<p><strong>2-Month Performance Trend</strong></p>
<ul>
<li><strong>Share of Voice increased from 5.4% → 9.4%</strong></li>
<li><strong>Your Brand Mentions grew from 117 → 1,046</strong></li>
</ul>
<p><img src="/case-studies/2026/02/Aesthetic-Clinic-Drove-52-a.png" alt="Aesthetic Clinic Drove 52% a" loading="lazy" decoding="async" /></p>
<h2>What Was Done (Strategy Breakdown)</h2>
<h3>1. AI Visibility Baseline &amp; Gap Identification</h3>
<ul>
<li>
Measured brand mentions, citations, and rankings across 400 tracked AI responses.</li>
<li>
Identified prompts where competitors were referenced more frequently.</li>
<li>
Prioritised treatment-related prompts with commercial intent.</li>
</ul>
<h3>2. Treatment-Level AEO Optimisation</h3>
<ul>
<li>Refined treatment pages to improve clarity around:
<ul>
<li>Suitability</li>
<li>Benefits vs alternatives</li>
<li>Safety considerations</li>
</ul>
</li>
<li>Structured our content in answer-ready formats, preferred by AI systems.</li>
</ul>
<h3>3. Authority &amp; Trust Reinforcement</h3>
<ul>
<li>Strengthened brand–procedure associations.</li>
<li>Reduced ambiguous phrasing that can cause AI systems to default to neutral or larger competitors.</li>
<li>Improved contextual cues AI models rely on for citation confidence.</li>
</ul>
<h3>4. Continuous Tracking &amp; Iteration</h3>
<ul>
<li>Monitored changes in share of voice and brand mentions weekly.</li>
<li>Validated improvements through ranking and citation movement, not assumptions.</li>
<li>Adjusted optimisation focus based on prompt-level performance.</li>
</ul>
<h2>Why Tracking AI Visibility Matters for Aesthetic Clinics</h2>
<ul>
<li>AI systems increasingly influence early treatment consideration.</li>
<li>Visibility loss doesn’t always show up in search rankings.</li>
<li>Patients often form perceptions before visiting a clinic’s website.</li>
</ul>
<h3>Without measurement:</h3>
<ul>
<li>Clinics don’t know which procedures AI associates with their brand.</li>
<li>Competitor visibility gaps remain hidden.</li>
</ul>
<h3>With tracking:</h3>
<ul>
<li>Share of voice becomes measurable.</li>
<li>Improvements can be validated over time.</li>
<li>Strategy shifts from reactive to data-led.</li>
</ul>
<h2>What This Case Study Signals</h2>
<p>This clinic did not chase traffic alone.</p>
<p>They focused on understanding how AI systems interpret credibility, treatment relevance, and brand authority.</p>
<p>As healthcare and aesthetic discovery increasingly shifts toward AI-generated answers, visibility is not about being searchable, but about being referenced and recommended.</p>
<p>Platforms like <a href="/"><em><strong>Zicy</strong></em></a> make this visibility measurable, enabling brands to adapt as AI-driven discovery continues to evolve.</p>
<p><em>For more AEO/GEO case studies, visit us at <strong><a href="/case-studies">https://www.zicy.com/case-studies</a></strong></em></p>`,
  },
  {
    slug: "aeo-geo-case-study-b2b",
    indexMeta: "B2B · AEO/GEO",
    eyebrow: "B2B · AEO/GEO",
    indexTitle: "Authority earned from a near-zero baseline",
    big: "90.61%",
    indexSub: "mentions · 55.92% citations",
    h1: "How a B2B Brand Achieved 90.61% AI Brand Mentions, 55.92% Citations &18.11% Share of Voice",
    metaTitle: "AI Brand Mentions + Citations Growth for B2B Brand — Zicy",
    metaDescription: "Discover how a B2B brand achieved 90.61% Brand Mentions, 55.92% Citations and increased Share of Voice by optimising visibility across AI platforms!",
    datePublished: "2026-03-11",
    dateModified: "2026-05-06",
    bodyHtml: `<p><strong><em>If AI had to recommend a service provider in your category today, would it choose you?</em></strong></p>
<p>In advisory-led industries, credibility is everything.</p>
<p>But credibility is no longer shaped only by search rankings or paid placements. It is increasingly shaped by how AI platforms surface, compare, and reference brands when users ask category-defining questions.</p>
<p>This <strong>B2B service provider</strong> wanted to understand one critical layer of visibility: <em>How consistently are we being mentioned, cited, and ranked inside AI answers?</em></p>
<h2>Results snapshot (Zicy AI Visibility Report)...</h2>
<p><strong>AI Authority &amp; Presence</strong></p>
<p>Across 150 tracked prompts and 5 AI platforms, the brand maintained consistent visibility inside AI-generated responses.</p>
<ul>
<li><strong>Brand Mention Coverage:</strong> <strong>90.61% </strong>(222 out of 245 AI responses included the brand).</li>
<li><strong>Website Citation Coverage:</strong> <strong>55.92% </strong>(137 out of 245 responses directly cited official URLs).</li>
<li><strong>Average AI Ranking:</strong> <strong>2.17</strong></li>
<li><strong>Share of Voice:</strong> <strong>18.11%</strong></li>
</ul>
<p><img src="/case-studies/2026/03/b2b-brand-Report-snapshot.png" alt="b2b brand Report snapshot" loading="lazy" decoding="async" /></p>
<p><strong>11-Week Visibility Movement</strong></p>
<ul>
<li><strong>Share of Voice</strong> increased from <strong>16.1% to 18.1%.</strong></li>
<li>Stable upward trajectory rather than one-off spikes.</li>
<li>Ranking consistency remained within top-tier positions.</li>
</ul>
<p><img src="/case-studies/2026/03/top-5-AI-performance.png" alt="top 5 AI performance" loading="lazy" decoding="async" /></p>
<p><strong>Competitive AI Positioning</strong></p>
<p>Against five direct competitors:</p>
<ul>
<li>Maintained <strong>#2.2 average AI ranking.</strong></li>
<li>Achieved the <strong>highest Share of Voice (18.1%).</strong></li>
</ul>
<p><img src="/case-studies/2026/03/Competitive-AI-Positioning.png" alt="Competitive AI Positioning" loading="lazy" decoding="async" /></p>
<h2>What was done (Strategic breakdown)</h2>
<ol>
<li><strong> AI Visibility Benchmarking</strong></li>
</ol>
<ul>
<li>Established baseline metrics across 150 tracked prompts.</li>
<li>Measured brand presence, citations, and rankings across 5 AI platforms.</li>
<li>Identified prompts where competitors were referenced more frequently.</li>
</ul>
<ol start="2">
<li><strong> Prompt-Level Optimisation</strong></li>
</ol>
<ul>
<li>Prioritised high-intent advisory and comparison queries.</li>
<li>Refined content clarity to improve AI attribution confidence.</li>
<li>Strengthened answer-structured sections within core service pages.</li>
</ul>
<ol start="3">
<li><strong> Entity &amp; Context Reinforcement</strong></li>
</ol>
<ul>
<li>Improved brand–service association signals.</li>
<li>Reduced ambiguous phrasing that can dilute AI citation likelihood.</li>
<li>Structured explanations in ways aligned with AI summarisation patterns.</li>
</ul>
<ol start="4">
<li><strong> Continuous Tracking &amp; Iteration</strong></li>
</ol>
<ul>
<li>Monitored weekly share of voice movement.</li>
<li>Used ranking and citation deltas to validate adjustments.</li>
<li>Focused on consistency rather than temporary spikes.</li>
</ul>
<h2>The broader signal….</h2>
<p>In high-trust industries, visibility is about being referenced when AI systems summarise, compare, and recommend.</p>
<p>As discovery models evolve, the brands that understand how they are surfaced inside AI answers will adapt faster than those relying solely on traditional search metrics.</p>
<p>Platforms like <a href="/"><strong>Zicy</strong></a> make this layer observable, so organisations can respond to how AI-driven discovery is actually unfolding.</p>
<p><em>For more AEO/GEO case studies, visit us at </em><a href="/case-studies"><em>https://www.zicy.com/case-studies</em></a></p>`,
  },
  {
    slug: "aeo-geo-case-study-elevated-b2b-visibility",
    indexMeta: "B2B · 5 AI platforms",
    eyebrow: "B2B · 5 AI platforms",
    indexTitle: "Consistent presence across five engines",
    big: "54.17%",
    indexSub: "mentions · 36.11% citations",
    h1: "How 54.17% Mentions & 36.11% Citations Across 5 AI Platforms Elevated B2B Visibility",
    metaTitle: "AI Brand Mentions + Citations Growth for B2B Across 5 platforms — Zicy",
    metaDescription: "Learn how this B2B brand achieved 54.17% Brand Mentions, 36.11% Citations & 8.31% Share of Voice by optimising visibility across AI platforms!",
    datePublished: "2026-03-16",
    dateModified: "2026-05-06",
    bodyHtml: `<p><em><strong>When AI compares service providers in your category, where do you appear?</strong></em></p>
<p>In B2B industries, discovery often begins with research-heavy queries and comparisons, “best provider” searches, and service-specific questions.</p>
<p>This provider wanted to answer a simple but strategic question: <strong>How visible are we inside AI-generated answers when buyers evaluate options?</strong></p>
<p>Instead of guessing, they tracked it.</p>
<h2><strong>AI visibility snapshot (Results using Zicy)</strong></h2>
<p>Across <strong>130 tracked prompts</strong> and <strong>5 AI platforms</strong>, the performance baseline showed:</p>
<ul>
<li><strong>Brand Mention Coverage:</strong> <strong>54.17%</strong> (78 out of 144 responses included the brand)</li>
<li><strong>Website Citation Coverage:</strong> <strong>36.11%</strong> (52 out of 144 responses directly referenced official URLs)</li>
<li><strong>Share of Voice:</strong> <strong>8.31%</strong></li>
<li><strong>Average AI Ranking:</strong> <strong>2.37</strong></li>
</ul>
<p><img src="/case-studies/2026/03/AI-Visibility-report-Across-130-tracked-prompts-and-5-AI-platforms-1018x1024.jpg" alt="AI Visibility report Across 130 tracked prompts and 5 AI platforms" loading="lazy" decoding="async" /></p>
<p><strong>Tracking individual queries revealed:</strong></p>
<ul>
<li><strong>Strong presence</strong> on high-intent “best provider” searches.</li>
<li><strong>Strong brand mention coverage</strong> on ChatGPT, Gemini, Perplexity, Google AI Mode, and AI overviews.</li>
<li><strong>Consistent top-three positioning</strong>.</li>
<li><strong>Higher share of voice</strong> on service-specific prompts.</li>
</ul>
<p><img src="/case-studies/2026/03/individual-tracked-prompts-1024x593.png" alt="individual tracked prompts" loading="lazy" decoding="async" /></p>
<h2><strong>What changed strategically</strong></h2>
<p>Rather than focusing on volume, the strategy focused on <strong>precision and reinforcement</strong>.</p>
<ol>
<li><strong>Query-Specific Content Alignment</strong></li>
</ol>
<ul>
<li>Mapped tracked prompts to existing service pages.</li>
<li>Strengthened structured answer sections.</li>
<li>Reduced generic positioning language.</li>
</ul>
<ol start="2">
<li><strong>Citation Optimisation</strong></li>
</ol>
<ul>
<li>Improved clarity of service explanations.</li>
<li>Added clearer attribution signals within core pages.</li>
<li>Enhanced internal linking for contextual reinforcement.</li>
</ul>
<ol start="3">
<li><strong>Ranking Stability Focus</strong></li>
</ol>
<ul>
<li>Monitored weekly ranking movement.</li>
<li>Prioritised prompts fluctuating outside top positions.</li>
<li>Adjusted content framing to improve summarisation probability.</li>
</ul>
<ol start="4">
<li><strong>Platform-Wide Monitoring</strong></li>
</ol>
<ul>
<li>Compared performance across platforms.</li>
<li>Identified where competitor mentions were stronger.</li>
<li>Focused optimisation on prompts with competitive pressure.</li>
</ul>
<h2><strong>And why this level of tracking matters</strong></h2>
<p>In B2B decision cycles:</p>
<ul>
<li>AI tools increasingly shape early vendor shortlists.</li>
<li>Buyers trust brands repeatedly surfaced across platforms.</li>
<li>Visibility gaps rarely show up in traditional analytics.</li>
<li>Citation frequency influences perceived authority.</li>
</ul>
<p>Without structured AI visibility tracking:</p>
<ul>
<li>You may rank on Google, but be absent in AI answers.</li>
<li>Competitors may be cited where you are not.</li>
<li>Share of voice shifts go unnoticed until pipeline impact appears.</li>
</ul>
<p>With tracking:</p>
<ul>
<li>Authority becomes measurable.</li>
<li>Prompt-level weaknesses become actionable.</li>
<li>Competitive positioning becomes transparent.</li>
</ul>
<h2><strong>The broader shift..</strong></h2>
<p>B2B discovery is evolving quietly.</p>
<p>Buyers are asking AI to compare, recommend, summarise, and shortlist before visiting a website.</p>
<p>The brands that understand how they appear inside those AI responses will adapt faster than those measuring search rankings alone.</p>
<p>Tools like <a href="/">Zicy</a> exist to surface that layer, so visibility inside AI answers becomes something you can track and improve.</p>
<p><em>For more AEO/GEO case studies, visit us at</em> <a href="/case-studies"><em>https://www.zicy.com/case-studies</em><br />
</a></p>`,
  },
  {
    slug: "aeo-geo-case-study-education-brand",
    indexMeta: "Education · 5 AI platforms",
    eyebrow: "Education · 5 AI platforms",
    indexTitle: "Cited across every major engine",
    big: "56.32%",
    indexSub: "mentions · 51.05% citations",
    h1: "How an Education Brand Reached 56.32% AI Mentions, 51.05% Citations Across 5 AI Platforms",
    metaTitle: "AI Brand Mentions + Citations Growth for Education Brand — Zicy",
    metaDescription: "Discover how a popular education sector client achieved 56.32% AI Mentions, 51.05% Citations  across five AI platforms!",
    datePublished: "2026-04-01",
    dateModified: "2026-05-06",
    bodyHtml: `<p><strong><em>If AI were asked to recommend institutions in your category today, would your brand make the shortlist?</em></strong></p>
<p>For this education-sector client, AI visibility was inconsistent across platforms.</p>
<p>The results show what structured AEO execution can achieve.</p>
<h2><strong>Results Snapshot (<a href="/">Zicy</a> AI Visibility Report + Analytics)</strong></h2>
<p><strong>AI Visibility &amp; Authority Signals</strong></p>
<ul>
<li><strong>Brand Mention Coverage:</strong> 56.32%</li>
<li><strong>Website Citation Coverage:</strong> 51.05%</li>
<li><strong>Share of Voice:</strong> 12.47%</li>
</ul>
<p><strong>Average AI Ranking:</strong> 2.98 across tracked prompts</p>
<p><img src="/case-studies/2026/04/Zicy-AI-Visibility-Report.png" alt="Zicy AI Visibility Report" loading="lazy" decoding="async" /></p>
<h3>Competitive Positioning (Top 5 Brands Tracked)</h3>
<ul>
<li>Brand ranked within <strong>Top 3 positions</strong> on average.</li>
<li>Achieved <strong>12.5% Share of Voice</strong>, outperforming competitors at 8.2%, 3.3%, 3.2%, and below.</li>
<li>Highest overall citation volume among tracked brands (97 citations).</li>
</ul>
<p><img src="/case-studies/2026/04/competitive-AI-performance-1024x270.png" alt="competitive AI performance" loading="lazy" decoding="async" /></p>
<p><img src="/case-studies/2026/04/individual-tracked-prompts-1024x610.png" alt="individual tracked prompts" loading="lazy" decoding="async" /></p>
<h3>Citation Analysis</h3>
<ul>
<li>149 Owned Authority citations.</li>
<li>529 Earned Authority citations.</li>
<li>197 Competitor citations monitored.</li>
</ul>
<p>This gave clarity on influence, not just mentions.</p>
<p><img src="/case-studies/2026/04/citation-analysis-1024x625.png" alt="citation analysis" loading="lazy" decoding="async" /></p>
<h3>AI Traffic Impact (GA4 – Dec 19 to Mar 18)</h3>
<ul>
<li><strong>218 AI-driven sessions</strong></li>
<li><strong>109 engaged sessions</strong></li>
<li><strong>50% engagement rate</strong></li>
<li>AI traffic contributed to form submissions, WhatsApp enquiries, and multi-session engagement.</li>
</ul>
<p><img src="/case-studies/2026/04/sessions-and-engagements-1024x668.png" alt="sessions and engagements" loading="lazy" decoding="async" /></p>
<h2><strong>What We Changed (Strategy)</strong></h2>
<p><strong>1. Prompt-Level Visibility Mapping</strong></p>
<ul>
<li>Tracked <strong>38 high-conversion-intent prompts</strong> across 5 major AI platforms.</li>
<li>Identified specific gaps in <strong>mention density</strong> and <strong>citation frequency</strong>.</li>
<li>Prioritized prompts that signaled strong commercial intent from prospective students.</li>
</ul>
<p><strong>2. Entity Strengthening &amp; Structured Authority</strong></p>
<ul>
<li>Reinforced institutional positioning by implementing:
<ul>
<li><strong>Clear definitional statements</strong> to help AI categorize the brand accurately.</li>
<li><strong>Program-specific structured sections</strong> for better indexing and retrieval.</li>
<li><strong>FAQ blocks</strong> specifically aligned with AI extractability requirements.</li>
</ul>
</li>
</ul>
<p><strong>3. Citation Ecosystem Expansion</strong></p>
<ul>
<li>Analyzed the balance between <strong>"Earned Authority"</strong> (third-party mentions) vs. <strong>"Owned Authority"</strong> (brand-controlled content).</li>
<li>Strengthened the technical authority of pages most likely to be used as primary citations by LLMs.</li>
</ul>
<p><strong>4. Share of Voice Optimisation</strong></p>
<ul>
<li>Identified specific query clusters where competitors were appearing more frequently.</li>
<li>Optimized content for <strong>comparison-style queries</strong> (e.g., "Brand A vs Brand B").</li>
<li>Improved contextual relevance to ensure inclusion inside multi-brand AI recommendations.</li>
</ul>
<p><strong>5. AI Traffic Measurement</strong></p>
<ul>
<li>Connected AI brand mentions to actual <strong>website sessions and engagement metrics</strong>.</li>
<li>Measured <strong>event triggers</strong> such as form submissions and WhatsApp inquiries.</li>
<li>Shifted from "visibility vanity" to focusing on <strong>measurable student intent</strong>.</li>
</ul>
<h2><strong>Why Tracking AI Visibility Matters</strong></h2>
<p>Education is a <strong>high-consideration</strong> journey. When AI answers specific student queries, such as:</p>
<ul>
<li><em>“Best institutions for X program”</em></li>
<li><em>“Top colleges for Y field”</em></li>
<li><em>“Where to study Z in [location]”</em></li>
</ul>
<p><strong>The brand that appears repeatedly becomes the default recommendation.</strong></p>
<p><strong>The Risks of Staying "Blind" to AI:</strong></p>
<ul>
<li><strong>Zero Awareness:</strong> You don’t know if your brand is even being mentioned in AI-driven searches.</li>
<li><strong>Citation Loss:</strong> You don’t know who is being cited as the authority instead of you.</li>
<li><strong>Influence Gaps:</strong> You can’t identify which specific prompts are driving market influence.</li>
<li><strong>Competitive Risk:</strong> You can’t defend your brand against competitors actively shaping AI narratives.</li>
</ul>
<p>Winning here is not about writing longer blogs; it’s about <strong>structured, extractable authority.</strong> If your institution has a visibility gap, it is measurable—and once it’s measurable, it’s optimisable.</p>
<p><em>For more AEO/GEO case studies, visit us at: </em><a href="/case-studies">https://www.zicy.com/case-studies</a></p>`,
  },
  {
    slug: "aeo-case-study-b2b-brand-mentions-ai-sessions-growth",
    indexMeta: "B2B services · 90 days",
    eyebrow: "B2B services · 90 days",
    indexTitle: "Full programme, no prior AI strategy",
    big: "56.67%",
    indexSub: "mentions · 2,971 AI sessions",
    h1: "How a B2B Brand Captured 56.67% AI Mentions and Generated 2,971 AI Sessions in 90 Days",
    metaTitle: "AEO/GEO Case Study: B2B Brand Mentions + AI Sessions — Zicy",
    metaDescription: "Learn how this B2B brand increased their AI brand mentions to 56.67%, with 2971 total AI sessions, 40% citations & more in just 90 days!",
    datePublished: "2026-04-07",
    dateModified: "2026-05-06",
    bodyHtml: `<p><em><strong>AI is quietly becoming the first stage of B2B vendor selection. </strong></em></p>
<p><em><strong>Are you showing up there?</strong></em></p>
<p>For this B2B client, traditional visibility wasn’t enough.</p>
<p>The real objective was measurable authority inside AI-generated responses and translating that into pipeline activity.</p>
<h2>Results Snapshot (<a href="/">Zicy</a> AI Visibility + Engagement Data)</h2>
<h3>AI Visibility Metrics</h3>
<ul>
<li><strong>Brand Mentions Coverage:</strong> 56.67%</li>
<li><strong>Website Citations Coverage:</strong> 40%</li>
<li><strong>Share of Voice:</strong> 7.75%</li>
<li><strong>Average AI Ranking:</strong> 2.56 (Consistently positioned within Top 3 across tracked prompts)</li>
</ul>
<p><img src="/case-studies/2026/04/B2B-Brand-AI-Visibility-Report.png" alt="B2B Brand AI Visibility Report" loading="lazy" decoding="async" /></p>
<h3>Prompt-Level Performance</h3>
<p>Across tracked high-intent prompts:</p>
<ul>
<li><strong>5/5 coverage</strong> on priority queries.</li>
<li><strong>Strong Share of Voice</strong> across:
<ul>
<li>ChatGPT</li>
<li>Gemini</li>
<li>Perplexity</li>
<li>Google AI Mode</li>
<li>AI Overviews.</li>
</ul>
</li>
</ul>
<p><img src="/case-studies/2026/04/AI-Driven-Traffic-Impact-1024x480.png" alt="AI-Driven Traffic Impact" loading="lazy" decoding="async" /></p>
<h3>AI-Driven Traffic Impact (GA4)</h3>
<p><em>3 Jan – 2 Apr 2026 vs previous period</em></p>
<ul>
<li><strong>2,971 AI sessions</strong></li>
<li><strong>2,093 engaged sessions</strong></li>
<li><strong>70.45% engagement rate</strong></li>
<li><strong>31,707 total events</strong></li>
<li><strong>113 key events</strong> (CTA clicks/conversions)</li>
</ul>
<p>Traffic breakdown:</p>
<ul>
<li>ChatGPT: 2,642 sessions (88.9%);</li>
<li>Gemini: +263% growth</li>
</ul>
<p><img src="/case-studies/2026/04/Traffic-breakdown-1024x689.png" alt="Traffic breakdown" loading="lazy" decoding="async" /></p>
<h2>What We Did (Strategic Adjustments)</h2>
<h3>1. Prompt-Level Gap Analysis</h3>
<ul>
<li>Identified which commercial and comparison prompts lacked visibility.</li>
<li>Prioritized high-value B2B decision queries</li>
<li>Tracked multi-platform consistency.</li>
</ul>
<h3>2. Entity Reinforcement &amp; Clarity</h3>
<ul>
<li>
<ul>
<li>Strengthened definitional authority.</li>
<li>Clarified service positioning for AI extraction.</li>
<li>Reduced ambiguity in category descriptions.</li>
</ul>
</li>
</ul>
<h3>3. Citation Optimisation</h3>
<ul>
<li>Structured content to increase citation eligibility.</li>
<li>Improved page-level extractability.</li>
<li>Balanced owned authority vs third-party mentions.</li>
</ul>
<h3>4. Competitive Share of Voice Monitoring</h3>
<ul>
<li>Measured how often competitors were mentioned in the same prompts.</li>
<li>Optimised content where competitor density was higher.</li>
</ul>
<h3>5. AI Traffic Attribution</h3>
<ul>
<li>Connected AI mentions to actual sessions and key events.</li>
<li>Tracked CTA clicks and engagement behaviour.</li>
<li>Validated AI as a performance channel, not just a branding layer.</li>
</ul>
<h2>Why This Matters for B2B Brands</h2>
<p>In B2B:</p>
<ul>
<li>Buyers research deeply before speaking to sales.</li>
<li>AI platforms are increasingly used for vendor shortlisting.</li>
<li>Decision-makers compare providers conversationally.</li>
</ul>
<p>If your brand:</p>
<ul>
<li>Isn’t mentioned,</li>
<li>Isn’t cited,</li>
<li>Or ranks below competitors in AI answers,</li>
</ul>
<p>You are losing influence before the first meeting.</p>
<p>Traditional SEO visibility does not reveal this. AI visibility requires its own measurement layer.</p>
<h2>The Bigger Shift</h2>
<p>AI is becoming the first filter in B2B decision-making.</p>
<p>Buyers:</p>
<ul>
<li>Ask for comparisons.</li>
<li>Ask for “best providers.”</li>
<li>Ask for regional expertise.</li>
<li>Ask for alternatives.</li>
</ul>
<p>The brand that appears repeatedly becomes the perceived category leader.</p>
<p>AI visibility can be measured, strengthened, and translated into meaningful engagement.</p>
<p>The shift isn’t coming.</p>
<p>It’s already here.</p>
<p>If you don’t know how often AI mentions your brand, someone else is shaping that narrative.</p>
<p>Platforms like <a href="/">Zicy</a> help you see it, track it, and optimise it.</p>
<p><em>For more AEO/GEO case studies, visit us at: </em><a href="/case-studies">https://www.zicy.com/case-studies</a></p>`,
  },
  {
    slug: "aeo-geo-case-study-interior-decor",
    indexMeta: "Interior décor · AEO/GEO",
    eyebrow: "Interior décor · AEO/GEO",
    indexTitle: "Cross-platform citation growth",
    big: "66%",
    indexSub: "mentions · 47% citations · 19% SOV",
    h1: "How an Interior Décor Brand Captured 66% AI Mentions, 47% Citations & 19% Share of Voice",
    metaTitle: "AI Brand Mentions + Citations Growth for Interior Decor Brand — Zicy",
    metaDescription: "See how a commercial interior brand hit 66.67% Mentions, 47.13% Citations & 19% Share of Voice by optimising for AI visibility. Learn the strategy here!",
    datePublished: "2026-04-21",
    dateModified: "2026-05-06",
    bodyHtml: `<p>The first comparison your buyers see might not be your brochure, but an AI response.</p>
<p>In the commercial interiors niche, influence now begins before the inquiry.</p>
<p>For this B2B interior décor client, AI visibility wasn’t accidental. It was measured, optimised, and expanded across five AI platforms.</p>
<h2>Results Snapshot (AI Visibility + Engagement)</h2>
<p><strong>AI Visibility Metrics</strong></p>
<ul>
<li><strong>Brand Mention Coverage:</strong> 66.67%</li>
<li><strong>Website Citation Coverage:</strong> 47.13%</li>
<li><strong>Share of Voice:</strong> 19.78%</li>
<li><strong>Average AI Ranking:</strong> #2.31</li>
</ul>
<p><img src="/case-studies/2026/04/AI-Visibility-Report-1024x423.png" alt="AI Visibility Report" loading="lazy" decoding="async" /></p>
<p><strong>Competitive Positioning</strong></p>
<p>Across 5 competing brands:</p>
<ul>
<li>Client achieved <strong>116 brand mentions</strong> vs competitors (17–42_.</li>
<li><strong>19.8% Share of Voice</strong>, significantly ahead of competitors at 4.7%, 2.3%, 1.2%, and below.</li>
<li>Highest citation count (82) among tracked brands.</li>
<li>Strong average sentiment score (78).</li>
</ul>
<p><img src="/case-studies/2026/04/Competitive-AI-Performance-1-1024x258.png" alt="Competitive AI Performance" loading="lazy" decoding="async" /></p>
<p><img src="/case-studies/2026/04/Key-Topics-1024x259.png" alt="Key Topics" loading="lazy" decoding="async" /></p>
<p><strong>Tracked High-Intent Prompts</strong></p>
<ul>
<li>Majority of priority prompts achieved <strong>4/5 or 5/5 brand coverage.</strong></li>
<li>Consistent <strong>Top 3 average positions</strong> across platforms.</li>
</ul>
<p><img src="/case-studies/2026/04/individual-tracked-prompts-1-1024x975.png" alt="individual tracked prompts" loading="lazy" decoding="async" /></p>
<p><strong>AI Referral Traffic Impact (Jan 17 – Apr 16)</strong></p>
<p>While AI traffic volume is not massive(which is typical in B2B niches like interior décor), engagement quality tells a stronger story:</p>
<ul>
<li><strong>297 AI sessions</strong></li>
<li><strong>156 engaged sessions</strong></li>
<li><strong>52.53% engagement rate</strong></li>
</ul>
<p><img src="/case-studies/2026/04/sessions-1024x639.png" alt="sessions" loading="lazy" decoding="async" /></p>
<p>For B2B and agency-style businesses where buying cycles are longer and volumes are naturally lower, this level of AI-driven engagement signals high-intent discovery rather than casual browsing.</p>
<h2>What We Did (Strategic Approach)</h2>
<ol>
<li><strong> Prompt-Level Visibility Mapping</strong>
<ul>
<li>Tracked high-intent commercial interior and specification queries.</li>
<li>Prioritised comparison and decision-stage prompts.</li>
</ul>
</li>
<li><strong>Topic-Level Authority Expansion (Brand Leaders, Battlegrounds, Blind Spots)</strong>Using Zicy’s key topics framework:
<ul>
<li><strong>Brand Leaders:</strong> Strengthened dominance in existing high-visibility interior décor themes.</li>
<li><strong>Battlegrounds:</strong> Reinforced competitive topics where multiple brands appear.</li>
<li><strong>Blind Spots:</strong> Identified uncovered areas for structured expansion and future growth.</li>
</ul>
</li>
<li><strong>Entity &amp; Extractability Optimisation</strong>
<ul>
<li>Strengthened category definitions and solution clarity.</li>
<li>Improved structured formatting for AI extraction.</li>
</ul>
</li>
<li><strong>Share of Voice </strong>
<ul>
<li>Analysed competitor density across prompts.</li>
<li>Reinforced areas with rising competitor presence.</li>
</ul>
</li>
<li><strong>AI Traffic Attribution</strong>
<ul>
<li>Analysed competitor density across prompts.</li>
<li>Reinforced areas with rising competitor presence.</li>
<li>Focused on sustained Top 3 positioning.</li>
</ul>
</li>
</ol>
<h2>Why This Matters for B2B Interior Décor Brands</h2>
<p>In commercial interior décor:</p>
<ul>
<li>Buyers research materials and solutions before vendor contact.</li>
<li>Architects and project managers validate options through AI summaries.</li>
</ul>
<p>If your brand:</p>
<ul>
<li>Doesn’t appear in specification-style queries,</li>
<li>Isn’t cited as a source,</li>
<li>Or ranks below competitors in AI summaries,</li>
</ul>
<p>You lose influence before the RFQ stage.</p>
<p>Traditional SEO metrics don’t reveal this layer. AI visibility requires its own tracking system.</p>
<p>Tools like <a href="/">Zicy</a> make that visibility measurable and actionable.</p>
<p><em>For more AEO/GEO case studies, visit us at </em><a href="/case-studies"><em>https://www.zicy.com/case-studies</em></a></p>`,
  },
  {
    slug: "aeo-geo-case-study-b2b-electronics",
    indexMeta: "B2B electronics",
    eyebrow: "B2B electronics",
    indexTitle: "Sessions and coverage, together",
    big: "157%",
    indexSub: "AI sessions growth · 40.56% mentions",
    h1: "How a B2B Electronics Brand Increased AI Sessions by 157% & Strengthened 40.57% Brand Mention Coverage",
    metaTitle: "AI Sessions + Brand Mention Growth for B2B Brand — Zicy",
    metaDescription: "Discover how a B2B electronics client achieved 40.56% Brand Mentions, 34.44% Citations, and 157.77% AI sessions growth!",
    datePublished: "2026-05-06",
    dateModified: "2026-05-06",
    bodyHtml: `<p>When engineering firms and technical buyers ask AI platforms about electronics solutions, which brands get cited?</p>
<p>For this B2B electronics client, AI visibility was not consistent across platforms. Through structured AEO optimisation, we improved mentions, citations, and engagement,  and translated that visibility into measurable AI-driven traffic.</p>
<p>Here’s what changed.</p>
<h2>Results Snapshot (AI Visibility + Traffic Impact)</h2>
<p><strong>AI Visibility Metrics</strong></p>
<ul>
<li><strong>Brand Mention Coverage</strong>: 40.56%</li>
<li><strong>Website Citation Coverage</strong>: 34.44.</li>
<li><strong>Share of Voice</strong>: 10.29%</li>
<li><strong>Average AI Ranking</strong>: #4.01</li>
</ul>
<p><img src="/case-studies/2026/05/AI-Visibility-Metrics.png" alt="AI Visibility Metrics" loading="lazy" decoding="async" /></p>
<p><img src="/case-studies/2026/05/Key-topics.png" alt="Key topics" loading="lazy" decoding="async" /></p>
<p><strong>Platform Breakdown:</strong></p>
<ul>
<li>AI Overviews (72.2%)</li>
<li>Google AI (58.3%)</li>
<li>Perplexity (47.2%)</li>
</ul>
<p><strong>AI Referral Traffic Growth (YoY)</strong></p>
<p><strong>Total AI Sessions:</strong></p>
<ul>
<li>1,158 sessions</li>
<li>+157.33% growth vs prior year</li>
</ul>
<p><strong>Engaged Sessions:</strong></p>
<ul>
<li>647 engaged sessions</li>
<li>+157.77% growth</li>
</ul>
<p><strong>Engagement Rate:</strong></p>
<ul>
<li>55.87%</li>
</ul>
<p><img src="/case-studies/2026/05/platform-breakdown-901x1024.png" alt="platform breakdown" loading="lazy" decoding="async" /></p>
<h2>What We Did (Strategic Approach)</h2>
<p><strong>1&#xfe0f;. Prompt-Level Visibility Mapping</strong></p>
<ul>
<li>Tracked electronics-specific high-intent queries and prompts.</li>
<li>Focused on multi-platform consistency.</li>
</ul>
<p><strong>2&#xfe0f;. Topic-Level Authority Expansion</strong></p>
<p>Using Zicy’s Key Topics framework:</p>
<ul>
<li>Strengthened dominance in core electronics collaboration and automation themes.</li>
<li>Reinforced content to improve share in overlapping visibility zones.</li>
<li>Surfaced underperforming topics.</li>
<li>Created a roadmap for the next optimisation phase.</li>
</ul>
<p><strong>3&#xfe0f;. Entity &amp; Technical Clarity Optimisation</strong></p>
<ul>
<li>Clarified product positioning for AI extraction.</li>
<li>Strengthened definitional authority around important topics.</li>
<li>Improved citation eligibility through structured formatting.</li>
</ul>
<p><strong>4&#xfe0f;. Share of Voice Stabilisation</strong></p>
<ul>
<li>Analysed competitor density per prompt cluster.</li>
<li>Reinforced prompts with declining ranking positions.</li>
<li>Focused on sustained visibility rather than isolated wins.</li>
</ul>
<h2>Why This Matters for B2B Electronics Brands</h2>
<p>In technical industries:</p>
<ul>
<li>Buyers research deeply before vendor outreach.</li>
<li>Engineers compare tools via conversational queries.</li>
<li>AI summaries influence shortlisting decisions.</li>
</ul>
<p>If your brand is:</p>
<ul>
<li>Mentioned inconsistently,</li>
<li>Cited less frequently than competitors,</li>
</ul>
<p>You lose influence before demos or RFQs begin.</p>
<p>Traditional SEO visibility doesn’t fully capture this layer. AI visibility requires its own measurement discipline.</p>
<h2>The Bigger Shift</h2>
<p>AI platforms are becoming technical comparison engines.</p>
<p>For electronics and engineering brands, visibility inside AI answers shapes:</p>
<ul>
<li>Vendor perception</li>
<li>Tool credibility</li>
<li>Integration confidence</li>
<li>Early-stage buyer trust</li>
</ul>
<p>The brands that understand how AI mentions, cites, and ranks them will shape the next wave of B2B discovery.</p>
<p><a href="/">Zicy</a> makes that visibility measurable and optimisable.</p>
<p><em>For more AEO/GEO case studies, visit us at <a href="/case-studies">https://www.zicy.com/case-studies</a> </em></p>`,
  },
];
